In [4]:
url = 'https://bit.ly/HDSC-StageOneDataset'

import pandas as pd

data_set = pd.read_csv(url)
data_set

,record_id,utility_id_ferc1,report_year,plant_name_ferc1,fuel_type_code_pudl,fuel_unit,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
0,f1_fuel_1994_12_1_0_7,1,1994,rockport,coal,ton,5377489.0,16.590,18.59,18.53,1.121
1,f1_fuel_1994_12_1_0_10,1,1994,rockport total plant,coal,ton,10486945.0,16.592,18.58,18.53,1.120
2,f1_fuel_1994_12_2_0_1,2,1994,gorgas,coal,ton,2978683.0,24.130,39.72,38.12,1.650
3,f1_fuel_1994_12_2_0_7,2,1994,barry,coal,ton,3739484.0,23.950,47.21,45.99,1.970
4,f1_fuel_1994_12_2_0_10,2,1994,chickasaw,gas,mcf,40533.0,1.000,2.77,2.77,2.570
...,...,...,...,...,...,...,...,...,...,...,...
29518,f1_fuel_2018_12_12_0_13,12,2018,neil simpson ct #1,gas,mcf,18799.0,1.059,4.78,4.78,9.030
29519,f1_fuel_2018_12_12_1_1,12,2018,cheyenne prairie 58%,gas,mcf,806730.0,1.050,3.65,3.65,6.950
29520,f1_fuel_2018_12_12_1_10,12,2018,lange ct facility,gas,mcf,104554.0,1.060,4.77,4.77,8.990
29521,f1_fuel_2018_12_12_1_13,12,2018,wygen 3 bhp 52%,coal,ton,315945.0,16.108,3.06,14.76,1.110
29522,f1_fuel_2018_12_12_1_14,12,2018,wygen 3 bhp 52%,gas,mcf,17853.0,1.059,0.00,0.00,11.680

In [46]:
data_set.tail(20)

,record_id,utility_id_ferc1,report_year,plant_name_ferc1,fuel_type_code_pudl,fuel_unit,fuel_qty_burned,fuel_mmbtu_per_unit,fuel_cost_per_unit_burned,fuel_cost_per_unit_delivered,fuel_cost_per_mmbtu
29503,f1_fuel_2018_12_191_1_14,191,2018,lawrence,coal,ton,1761218.0,17.888320,26.775,27.392,1.497
29504,f1_fuel_2018_12_191_1_15,191,2018,lawrence,gas,mcf,88846.0,1.031133,6.274,6.274,6.084
29505,f1_fuel_2018_12_432_0_2,432,2018,pueblo diesels,oil,bbl,81.0,5.694696,101.330,101.330,17.790
29506,f1_fuel_2018_12_432_0_5,432,2018,airport - pueblo,oil,bbl,133.0,5.756940,95.530,95.530,16.590
29507,f1_fuel_2018_12_432_0_8,432,2018,rocky ford diesels,oil,bbl,320.0,5.719602,98.180,98.150,17.160
29508,f1_fuel_2018_12_432_0_11,432,2018,airport - units 1&2,gas,mcf,2154971.0,1.130000,255.000,3.780,3.350
29509,f1_fuel_2018_12_432_0_14,432,2018,airport unit 6,gas,mcf,162132.0,1.130000,2.460,3.970,3.510
29510,f1_fuel_2018_12_403_0_2,403,2018,wygen 2,coal,ton,569800.0,16.110000,14.760,0.810,1.130
29511,f1_fuel_2018_12_403_0_6,403,2018,cheyenne prairie 42%,gas,mcf,613882.0,1.050000,3.520,3.520,3.360
29512,f1_fuel_2018_12_403_0_9,403,2018,cheyenne prairie,gas,mcf,19655.0,1.050000,8.910,8.910,8.480
29513,f1_fuel_2018_12_12_0_2,12,2018,ben french station,gas,mcf,39679.0,1.059000,5.680,5.680,5.360
29514,f1_fuel_2018_12_12_0_4,12,2018,ben french station,oil,bbl,487.0,5.831070,0.000,0.000,9.970
29515,f1_fuel_2018_12_12_0_7,12,2018,neil simpson unit 2,gas,mcf,18370.0,1.059000,8.330,8.330,15.930
29516,f1_fuel_2018_12_12_0_8,12,2018,neil simpson unit 2,coal,ton,491913.0,16.100000,14.760,17.720,1.100
29517,f1_fuel_2018_12_12_0_10,12,2018,wyodak - bhp 20%,coal,ton,409637.0,16.068000,13.690,14.310,0.890
29518,f1_fuel_2018_12_12_0_13,12,2018,neil simpson ct #1,gas,mcf,18799.0,1.059000,4.780,4.780,9.030
29519,f1_fuel_2018_12_12_1_1,12,2018,cheyenne prairie 58%,gas,mcf,806730.0,1.050000,3.650,3.650,6.950
29520,f1_fuel_2018_12_12_1_10,12,2018,lange ct facility,gas,mcf,104554.0,1.060000,4.770,4.770,8.990
29521,f1_fuel_2018_12_12_1_13,12,2018,wygen 3 bhp 52%,coal,ton,315945.0,16.108000,3.060,14.760,1.110
29522,f1_fuel_2018_12_12_1_14,12,2018,wygen 3 bhp 52%,gas,mcf,17853.0,1.059000,0.000,0.000,11.680

In [47]:
data_set.columns

Index(['record_id', 'utility_id_ferc1', 'report_year', 'plant_name_ferc1',
       'fuel_type_code_pudl', 'fuel_unit', 'fuel_qty_burned',
       'fuel_mmbtu_per_unit', 'fuel_cost_per_unit_burned',
       'fuel_cost_per_unit_delivered', 'fuel_cost_per_mmbtu'],
      dtype='object')

In [59]:
data_set.groupby('fuel_unit')['fuel_unit'].count()

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

In [63]:
data_set1= data_set[['fuel_unit']].fillna(value='mcf')
data_set1.isnull().sum()

fuel_unit    0
dtype: int64

In [69]:
ddata= data_set[0:1900].reset_index(drop='true')
sdata=  data_set[1900:].reset_index(drop='true')

mdat= pd.merge(ddata,sdata, how = "inner")
rdat= pd.merge(ddata,sdata, how = "outer")

In [71]:
import matplotlib.pyplot as plt
import seaborn as sns

In [74]:
sns.boxplot(x='fuel_cost_per_unit_burned', y= 'fuel_gty_burned')

ValueError: Could not interpret input 'fuel_cost_per_unit_burned'